version: "3.8"

services:
  frontend:
    container_name: viewtube-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    networks:
      - viewtube-network

  backend:
    container_name: viewtube-backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mongo
    networks:
      - viewtube-network

  mongo:
    container_name: viewtube-mongo
    image: mongo:7.0 #Supported until 2026
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - viewtube-network

volumes:
  mongo_data:

networks:
  viewtube-network:
    driver: bridge